### PR TITLE
Paragraph links

### PR DESCRIPTION
**Pull request by Bigtruck2**
I wrote a script with bun to create links to individual paragraphs as described in #123 . Just change the list of files in replace.js and run bun src/util/replace.js to create individual paragraph links.

### CODE REVIEW

**Comment by LiquidZulu** [comment]
My problems with this solution are:
1. I would need to get bun working (the astro site is not currently built with bun)
2. these would be completely randomly generated IDs, meaning that permalinks would be impossible (if the site was rebuilt, all of the per-paragraph links would change)
3. looks like this needs to be manually ran to add links to the files, would be far more parsimonious to introduce this as a remark plugin (see: [remarkPlugins](https://github.com/LiquidZulu/liquidzulu.github.io/blob/9f20573e384a9667162900d81433cf2664fdafed/astro.config.mjs#L33) and [markdown-plugins.ts](https://github.com/LiquidZulu/liquidzulu.github.io/blob/source/src/util/markdown-plugins.ts))

I do appreciate the PR, but this would not suit my use case at present. Thank you.

**Comment by LiquidZulu** [comment]
To elaborate on the final point (that it does not suit my use case): the way I want to be able to add content to this site is to just throw markdown files into the content directory and have everything else already working for me. I don't want to have to remember to run a script which updates those markdown files, any mapping of this sort should be done immutably in the remark plugins.

**Comment by Lord-Valen** [comment]
> I don't want to have to remember to run a script which updates those markdown files

You could run it in CI or as a pre-commit hook.

**Comment by LiquidZulu** [comment]
> > I don't want to have to remember to run a script which updates those markdown files
> 
> You could run it in CI or as a pre-commit hook.

That is true, but I was counting that under the umbrella of getting bun working

**Comment by Lord-Valen** [comment]
Looks like all you need is bun installed. The only dependencies are bun, grep, wc, and sed.

**Comment by LiquidZulu** [comment]
I tried getting bun working before and it was giving me problems (it might have been `bunx`). I do vividly remember trying to move the build scripts over to bun and it was just not happy. IDK if that was just it being in an early state or whatever, but its not a big deal (the site only needs to rebuild when I push new content to it, fast build times are not necessary).

**Comment by Lord-Valen** [comment]
I don't see any reason why this couldn't be done with a bash script or with node anyway.

**Comment by LiquidZulu** [comment]
Right, it would be trivial to translate the script to work with whatever other thing, but the other problems would still stand. The way I would be doing it is with a remark plugin (these are easy enough to write).

**Comment by Bigtruck2** [comment]
Something like this? https://github.com/Bigtruck2/liquidzulu.github.io/commit/0e2c6bf7821432f2e42821c43def4f95194e8488

**Comment by LiquidZulu** [comment]
Looks good, I will review it more thoroughly later, but that is definitely on the right tracks

**Comment by Bigtruck2** [comment]
I think doing what you did for the header links would be better than a Markdown plugin because I can't figure out how to do a Markdown plugin without regex. This is the paragraph highlighting with a client side script: https://github.com/LiquidZulu/liquidzulu.github.io/compare/source...Bigtruck2:liquidzulu.github.io:master

**Comment by LiquidZulu** [comment]
I don't like it being a client side script, because then people can't link directly to it and have the browser understand what that means. Pretty sure the headers are already picked out by remark---that is what I want done with the paragraphs. I'm fine with adding the link icons with a local script, but I just want there to be actual IDs for each paragraph provided by remark.

**Comment by Bigtruck2** [comment]
I think I found a solution. I used rehype instead of remark, but I had to remove the getMostCommonWords function because of duplicates. https://github.com/LiquidZulu/liquidzulu.github.io/compare/source...Bigtruck2:liquidzulu.github.io:master

**Comment by LiquidZulu** [comment]
Can you explain the purpose of the spread inside of a list seen [here](https://github.com/Bigtruck2/liquidzulu.github.io/blob/632ea7f522d8f7e7eb34005792c7ec4e95be6295/src/scripts/paragraphLinks.ts#L4)? Surely `[...blockquotes]` is equivalent to `blockquotes`, no?

**Comment by Bigtruck2** [comment]
You're right.

**Comment by Bigtruck2** [comment]
[...blockquotes] would have the splice function so that's why I used it for paragraphElements but blockquotes doesn't have any array function applied that would require doing that. I just removed it.

**Pull request closed without merging**
